2011a
fd1-53-17/Cherniavskiy pull request #11
Opened 2017-11-21 11:02 UTC by Cherniavskiy

2017-11-22 04:18 UTC, antonkulakov-it requested changes

2017-11-22 04:18 UTC, antonkulakov-it commented on 2011a/DZ/Chess/assets/style.css
> +div:nth-child(n):nth-child(-n+9):nth-child(even), div:nth-child(n+9):nth-child(-n+16):nth-child(odd),
не расставлены фигуры
буквы и цифры только по одной стороне

2017-11-22 17:22 UTC, Cherniavskiy commented on 2011a/DZ/Chess/assets/style.css
> +div:nth-child(n):nth-child(-n+9):nth-child(even), div:nth-child(n+9):nth-child(-n+16):nth-child(odd),
Готово

2017-11-24 05:31 UTC, antonkulakov-it approved these changes

2017-11-24 05:31 UTC, merged