2711a
fd1-53-17/Cherniavskiy pull request #16
Opened 2017-11-28 12:49 UTC by Cherniavskiy

2017-11-29 05:28 UTC, antonkulakov-it requested changes

2017-11-29 05:28 UTC, antonkulakov-it commented on 2711a/1/assets/style.css
> +        height: 50px;
На больших разрешениях пункты меню выйдут за границы блока nav

2017-11-29 05:37 UTC, Cherniavskiy commented on 2711a/1/assets/style.css
> +        height: 50px;
Исправил

2017-12-12 18:51 UTC, antonkulakov-it approved these changes

2017-12-12 18:51 UTC, merged